services:
 db:
   image: "ghcr.io/seuros/postgis-with-extensions:18"
   ports:
     - "5433:5432"
   environment:
     POSTGRES_PASSWORD: ubuntu
     POSTGRES_USER: ubuntu
     POSTGRES_DB: active_record_test